### PR TITLE
Fix an issue when unmarshaling NXActionNote

### LINKED ISSUE #19: ActionNote unmarshal seems incorrect.
https://github.com/contiv/libOpenflow/blob/7c65343907211dea3729e85d3a82b8d3863c6493/openflow13/nx_action.go#L1339

fix perhaps can be 
" a.Note = data[n: n+a.Length- a.NXActionHeader.Len()]"

The problem with this is that "func (a *NXActionNote) Len()" would return a length that is also the length of entire data byte stream. Thus if this NoteAction is part of multipart reply, the subsequent replies would not be processed,

### PR DESCRIPTION
**Pull request by wenyingd**
As the length of OVS "note" action is variable, we need to check the
action length in message header and load the bytes with given length
to avoid impacts on the subsequent OF messages.

Fixes #19

### CODE REVIEW

File: openflow13/nx_action.go [hunk 1]
```diff
@@ -1336,7 +1336,7 @@ func (a *NXActionNote) UnmarshalBinary(data []byte) error {
 		return errors.New("the []byte is too short to unmarshal a full NXActionNote message")
 	}
 	n := a.NXActionHeader.Len()
-	a.Note = data[n:]
+	a.Note = data[n:a.Length]
```
Comment (jojimt) [inline openflow13/nx_action.go:1339]: Does this mean that the passed data has trailing stale bytes?

Comment (wenyingd) [reply openflow13/nx_action.go:1339]: > Does this mean that the passed data has trailing stale bytes?

@jojimt  Since the function Instruction.UnmarshalBinary has passed all data to decode actions (https://github.com/contiv/libOpenflow/blob/master/openflow13/instruction.go#L207), it might read the bytes in the subsequent actions which leads to a mistake if here doesn't trail the data based on the length. So it would be secure to limit the bytes according to the length of the Note action when setting "Note" field.

**Review by jojimt — APPROVED** [review]
